sudo: false
language: java
jdk:
  - oraclejdk7
addons:
  apt:
    packages:
    - oracle-java7-installer
script: ./build.sh
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ef8645d0a8959f3f49c2
    on_success: change
    on_failure: always
    on_start: false
