sudo: false
language: java
jdk:
  - oraclejdk7
addons:
  sonarqube: true
  apt:
    packages:
    - oracle-java8-installer
script:
  - "./build.sh"
  - jdk_switcher use oraclejdk8
  - "./sonar.sh"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ef8645d0a8959f3f49c2
    on_success: change
    on_failure: always
    on_start: false
env:
  global:
  - secure: Q0AmjxrPpFTdsAwqbiwweQexDiIc5Nqq8MqnFvSHMZ2uDuubLmyWJ8fmLNrQu1Ph23g9cnmkHX8OFU9lE55IGQzmOMcN5k/iFlXXwtCvT7Iiv6GNquDtgPWWDAdkNmY5WPF5QUH4xw5sumD0G9UoaByq/d/TMYAr/j7LrhO6RJfV4nk/5XF8PXIRCQwMhlJvZE0KdQeEm8Q/KuB8J4pilQ6ZoNH1yzc28JTs7isxedCweKr4ZHorm2bpT4xK8B6he0BwZXQqghJys+zTOY778D1/rKnffKMSA88OkYlmDyKXPju30r84iVoMYRjfWxaHE3cef6Hqhxw6b+plUqKH4EHt8nLwiqmFRLAlw/4Qf610fnQujGwL1Www68AI8W6pwsLkOtYL5IBivxtqx6g1k8t9qy+hd17dqy/E8bnk3xZ6SqhC9gghZZtXnnZUkQLcYE0uYinLKN19VD84mYFQTeERWjqKhN4HAsawE9k8zH1AqHqcDJvhbHaklpQryu/43/y6fHCyBsA541GghRujIf200HjTYvEjkHLSVvnaiu05/Pj8e7WpBFS0H+Z3bRj724C0FpGHFx8exzbdAwhy/bgDnuMn1hQMO44HoldKCkvHopGa3r9nLTPn9T3BpE5JysE9amxBmh47WlRplvIwP1e0wgcFObmIhFNoJbeljUA=
  - secure: pTVtQzx1KTvtXzazKdLpsklFpNlOsk+p67ulkrBw8O1tsD3fWskQDTGhnIxw2o8pigpxtm1+FE9f9wWhO4Faz8rL7JA1PddNBiOA8d+Qm6zs4IYNUcbXacLKD5sJok0VGrwCs9KMPgzerfAHnZYXdxuzIiHGkrBe4PK7SMhwKexH1G0pfUMj+ZoPhvsB0eP1C1adknjpT793dtyj+RR1QFwJxY5qZkNF7GcBeo9GO2OYLrUMoLxTIi3tDsxwX0jZmG/eR1RgVCDcQgFoCWeSc8XVY60Ik5mR1j84wCdYWfZIF+KJUNtA5ryKL0O8sZSwWrm63fOLdJMhlCNu08/ECdzvyVXLUcNcx/PTjxed41gA5j4Cfkq54qk9LMonx12I29bAD4pyS+KsyqsIaD/ONg68O14phaZkHM6FrW0QvrhOVAcsO5RNq2YsbGnxHTYWhu3JnDeYL0/dM1+seDXjzgFShtGH7AUDAa1P6Po47JJzQeESPS9OI7F0GwH37wNrjC1o9wch7U8Ip8Y3WtGzqY4xwlslfdWEA2KLD+AFtvp5rrluDJXlBaMQwo402Uv2M2zkV+tP6WP4QP/BGbv3ocPGYS46NOwInalEKqJ22+KN1PSeRdzwHfb2bdj9h1XP3dMD+7G940Bf5PX/VDUJFTjsvxWL07l10ERBYVbXiNc=
